version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=["http://localhost","http://127.0.0.1","http://localhost:5173","http://127.0.0.1:5173"]
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 20
    command: >
      /bin/sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull qwen2.5-coder:7b-instruct &&
      tail -f /dev/null
      "

  web:
    image: nginx:alpine
    container_name: local-llm-web
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "5173:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  ollama_data: